### ISSUE TITLE
Record Individual Final Video

### ISSUE THREAD

**Issue by JakubPonulak** [JakubPonulak/flask_portfolio_hackers#13]
- [x] Anika - [Link](https://www.loom.com/share/d710203067df46b6bfacc488f30562a5)
- [x] Jakub - [Link](https://drive.google.com/file/d/1lmFd8p7Tu3iufImNV3NEabiw7Eq7j-Tv/view?usp=sharing=)
- [x] Tristan - [Link](https://drive.google.com/file/d/1yo1d4Epn89PAOz-8AyFBuIe8No6LpY1J/view?usp=sharing)
- [x] Vunsh [Link](https://drive.google.com/file/d/1vNNjPuGzr_rWB_qtAlLOTeWkgsct5Q2X/view?usp=sharing)

You will prepare a video between 2:30 to 3:15 minutes.  You will cover 3 topics in video.   Additionally, you will prepare 1 topic for live review during the following week with Teacher.  A total of 4 topics.  All preparations need to be from your own work.  At least 3 of 4 will be from CODE and supported by Journals, Issues, README, Preso's, etc.  One of the items can be from Processes or Activities you have performed to support the Scrum Team or Class.

Grading:

- 1 point.  Looking for a relationship between work presented and College Board topic.  Make this obvious, share number, topic, quiz question(s)!!!  .50 CB topic not really associated with PBL, .75 for CB to PBL correct, 1.0 for CBL to PBL brilliance.
- 1 point.  Demonstrating command of Technical Topic through PBL, ie Tour of Code. (.50 PBL topic fuzzy, .75 PBL topic OK, 1.0 PBL topic shows Command)

Anika's Video - [Link](https://www.loom.com/share/d710203067df46b6bfacc488f30562a5) - Average Score: 5.83/6

Team Member | CB Relationship | PBL Technical Command  | Comments | Score |
--- | --- | --- | --- | ---
Anika | N/A | N/A | N/A | N/A |
Jakub | 2.75/3 | 2.75/3 | 1+ Very Organized, easy to understand and follow along; good labels and explanation of each segment 2+ I liked that you showed both the frontend and the backend of every page you went over 3+ I like that you added information about our planning (implementing ideas from the wireframe), as it demonstrated progress towards the completed product  1- Code for the first topic was kind of vague, maybe go over specific parts of the HTML pages, like body, style, images, etc. | 5.5/6 |
Tristan | 3/3 | 3/3 | Your visuals were very good. It was very easy to follow with what you were doing and how the code performed on the website. Each topic you chose was thoroughly explained and you really did a good job on your presentation | 6/6 |
Vunsh | 3/3 | 3/3 | + Very straightforward and easy to follow, overall visually appealing and viewable. + Shows clear understanding of each topic and explanations as to why every part of the project exists. + Clearly showed the relationship between PBL learning and CB topic, even cited the specific unit. I liked how organized the visuals were, overall great job! | 6/6 |

Jakub's Video - [Link](https://drive.google.com/file/d/1lmFd8p7Tu3iufImNV3NEabiw7Eq7j-Tv/view) - Average Score: 5.92/6

Team Member | CB Relationship | PBL Technical Command | Comments | Score |
--- | --- | --- | --- | ---
Anika | 2.75/3 | 3/3 | (+) It is clear that you understand the code and the topics discussed in the videos thouroughly, your explanations were easy to follow (+) I like how when you referenced the code you went back to the READme, it shows that you regularly use and are comfortable with the organization tools and formats given to us, even after we have been graded on them (-) even though you mentioned the cb topic that each aspect of your video covered, it would have been better if you linked the sections to specific quizzes, tpt or tech talk presentations, or tpt assignments | 5.75/6 |
Jakub | N/A | N/A | N/A | N/A |
Tristan | 3/3 | 3/3 | Everything was simple and your flow was very well. You proved your understaning of the code effciently in the video. The topics you went into were in my opinion good topics.  I think your video hits every nail on the head, great job. | 6/6 |
Vunsh | 3/3 | 3/3 | + I love how everything was short and simple, but you still managed to get a lot of information in a short amount of time. + The binary explanation was excellent and it was clear you had a great understanding of the CB topic. The implementation of the topic onto the PBL was explained as well, with code explanations from displaying the Github. I liked how you did walk through some of the code on Github in addition to just showcasing the project. + Overall amazing work, its clear you have learned a lot in many different aspects from the PBL. | 6/6 |

Tristan's Video - [Link](https://drive.google.com/file/d/1yo1d4Epn89PAOz-8AyFBuIe8No6LpY1J/view?usp=sharing) - Average Score: 5.5/6

Team Member | CB Relationship | PBL Technical Command  | Comments | Score |
--- | --- | --- | --- | ---
Anika | 2.75/3 | 2.75/3 | (+) I like how you included many examples for each collegeboard topic, and went into each of them with great detail. (+) Your explanations were clear and easy to follow (+) your I liked te representations of your ideas (-) You could have been more specific when explaining the relation between the collegeboard topic and the pbl topic | 5.5/6 |
Jakub | 2.75/3 | 2.75/3 | 1+ You went over the code in detail, explained what each segment did, which made it easy to understand how the lines of code you showed related to your topic. 2+ I like that you included multiple examples of your work for each topic, it shows your understanding and of the topic and makes it easier to understand the general idea of the topic. 3+ Another thing I think you did well on was supporting your code and explanations with runtime examples from the website. Showing the actual website pages made it easier to visualize and understand what each topic was about and how it is part of coding, or in this case making a website. 1- I think that you should include a more detailed explanation of the College Board Topics. If you had explained more what each topic was about, instead of instantly going into the code/your examples, it would help to understand the ideas in general instead of in a specific situation. | 5.5/6 |
Tristan | N/A | N/A | N/A | N/A |
Vunsh | 2.75/3 | 2.75/3 | + Explained code very well, nice to hear your views on the specifics of the code rather than a generalized topic. + CB topic was explained well, many examples and ideas surrounding it were brought up. - Not much correlation between CB topic and PBL, could explain more. | 5.5/6 |

Vunsh's Video - [Link](https://drive.google.com/file/d/1vNNjPuGzr_rWB_qtAlLOTeWkgsct5Q2X/view?usp=sharing) - Average Score: 3.83/6

Team Member | CB Relationship | PBL Technical Command  | Comments | Score |
--- | --- | --- | --- | ---
Anika | 1.75/3 | 2/3 | (+) you explained the API and what contribution it made to our website really well (+) of the PBL topics you did explain, your it's evident that you are proficient in those aspects (+) the link between lists and your API was explained very well (-) your video was too long and you only went over 2 pbl topics  | 3.75/6 |
Jakub | 1.25/3 | 2.5/3 | 1+ There are a lot of details involved in the code you went over, it was easy to follow along and it clearly demonstrates your knowledge in coding and technical command. 2+ I think that it was good to include background/supporting information about the API. Instead of just going over what it is, you included how it works with other parts of the website, and what it needs to work, which I think was helpful to not only explain more about APIs but illustrate how it works in our website. 3+  It was helpful to see what the API does in terms of the front-end of our website. Showing the API working on our home page was a good idea, as it showed what it is actually used for and how our website benefits from it. 1- You should go more into detail about how your code connects to the College Board material, and you should also include a third section. I understand that the topics were APIs and Lists, but I am uncertain what the third topic was, if there was one.  | 3.75/6 |
Tristan | 1/3 | 3/3 | You went into great detail about your contribution and it was extremely easy to understand with your explanation. You showed all aspects of the API and that is really cool. The animation in the beginning was also pretty cool. I'm not sure if I missed it but it didn't look like you went into three TPT topics in the video and essentially just explained your contribution | 4/6|
Vunsh | N/A | N/A | N/A | N/A |

**Comment by CalissaT** [comment]
Vunsh's Score 
- Topic 1 (Variables): There was a very brief explanation of variables, although I felt like you could have expanded more since there were some labs that we did that included variables, and even in the API code. **0.5/2** 
- Topic 2 (Lists): Good explanation of lists and how it is implemented in your API by showing the raw, unformatted data. I also liked your explanation of how to access certain items in a list **2/2**
- Topic 3 (Dictionaries): There wasn't really much of an explanation for dictionaries, but it was mentioned in the video. Maybe you could've provided an example and compare/contrast lists and dictionaries. **0.25/2**

Positives:
-  I really liked the editing in the beginning [0:13]-[0:21]. I thought it was cool that you got the website over your code, and then it faded out in the end. 
- You did a very good job explaining the API and how it works, and its very apparent you have a solid understanding of APIs. 
- I think adding in how all the data from the API looks in your website supports the video very well. I like what you've done to make the page look nice with aesthetically pleasing colors. 

Improvements: 
- You needed to add two more PBL or minilab things to the video, maybe ones in which could help strengthen topics 1 and 3 would be ideal. 

Group comments: 
- You did a pretty good job providing feedback on your group members' videos. However I think it would be more helpful if your group gave each other feedback/evidence for the College Board and PBL Technical Command section **1.75/2**

Total Score: 4.75/8

**Comment by jm1021** [comment]
Essentially 1 of 3 topics, long video focus on Weather API and list/dictionary abstraction for front page temp in Celsius.
5/8 will be final.

**Comment by jm1021** [comment]
Tristan,  very nice job of flowing through labs and code.  I know you talked about iteration, conditionals, and algorithms.   In each you covered, introduction, code review, and demo.   Your language in describing and ability to find all the sections of code provided great command.  IMO, you covered CB topic well through your examples.   Perhaps improvement would have been a visual or slide to answer what your teammates requested.  6/6.

On your comments, I am always looking for comments that promote follow up and additional collaboration.  You comments are complementary (mostly), even where you suggested missing 3 topics it could have been a bit stronger.  Comments could have citations of work, including a specific to correct.  Remember, they are worth 2 points.  1.75/2
